id: P005485
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:53:04.197218
source_metadata:
  id: bdr:W1KG22610
  title: རིགས་ལམ་འཕྲུལ་གྱི་ལྡེ་མིག
  author: ''
  volumes:
    aeed51072eff422d9f828c7cfc122433:
      image_group_id: I1KG22647
      title: ''
      volume_number: 1
      total_pages: 182
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
